- name: Create group
  group:
    name: "{{group}}"

- name: Create the user 
  user:
    name: "{{user}}"
    comment: Srikanth D
    uid: 1040
    group: "{{group}}"

- name: Firewall add httpd
  firewalld:
    service: http
    permanent: yes
    state: enabled
  notify:
    - reload firewalld

- name: Flush handlers
  meta: flush_handlers

- name: Install package
  yum:
    name: "{{package}}"
    state: latest
  notify:
    - start httpd

- name: Copy httpd file
  copy:
    src: /etc/passwd
    dest: /etc/password.jumpserver 