- name: Download mysql communiry repository package 
  get_url:
    url: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    dest: /etc/mysql57-community-release-el7-9.noarch.rpm
    mode: '0440'

- name: Install myql repo package
  yum:
    name: /etc/mysql57-community-release-el7-9.noarch.rpm
    state: present

- name: Install myql-server  package
  yum:
    name: "{{mysql.package}}"
    state: present

- name: Start mysql service
  systemd:
    name: "{{mysql.service}}"
    enabled: yes
    state: started

- name: Read root password
  shell: cat /var/log/mysqld.log | grep 'temporary password' | awk {'print $11'}
  register: password

- name: print root password 
  debug:
    var: password.stdout_lines

- name: Set root user password
  mysql_user:
    name: root
    host: "{{ inventory_hostname }}"
    password: "{{ mysql.password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ password.stdout_lines }}"
    state: present

- name: Create new mysql user
  mysql_user:
    login_user: root
    login_password: "{{ mysql.password }}"
    name: "srikanth"
    password: "srikanth"
    priv: '*.*:ALL,GRANT'
    state: present
    host: "{{ inventory_hostname }}"