 - hosts: webservers
   vars:
    ansible_connection: ssh
    ansible_ssh_user: vagrant
    ansible_become: true
    package: net-tools
    user: alex
    group: linux
    tasks:
  - name: Create group
    group:
      name: "{{group}}"

  - name: Create the user 
    user:
      name: "{{user}}"
      comment: Alex
      uid: 1055
      group: "{{group}}"

  - name: Install package
    yum:
      name: "{{package}}"
      state: latest

  - name: Copy group file
    copy:
      src: /etc/group
      dest: /tmp/group.back

  - name: Create a directory 
    file:
      path: /tmp/linux
      state: directory
      mode: '0755'

  - name: Firewall add httpd
    firewalld:
      service: http
      permanent: yes
      state: enabled
    notify:
      - reload firewalld

  - name: Flush handlers
    meta: flush_handlers

  - name: Executing a Command Using Shell Module 
    shell: netstat -an > temp.txt

  - hosts: mysql
     tasks:
  - name: copying repo file
    copy:
      src: /etc/yum.repo.d/rhel.repo
      dest: /etc/yum.repos.d/rhel.repo
  - name: Install WGET
    yum: name=MySQL-python state=installed
  - name: Download lib
    get_url: url=http://repo.mysql.com/mysql-community-release-el7-6.noarch.rpm dest=/usr/mysql/mysql-community-release-el7-6.noarch.rpm
  - name: install rpm
    yum: name=/usr/mysql/mysql-community-release-el7-6.noarch.rpm state=present
  - name: Update Package
    yum: name=* state=latest
  - name: Install mySQL
    yum: name=mysql-server state=installed
  - name: Start SQL service
    service:name=mysql state=restarted
  - name: create demo database
    mysql_db: name=Kalyan state=present
  - name: create demo user
    mysql_user name=demo password=demo priv=demo *:ALL host='%' state=present
  - name: restart mysql
    service: name=mysql state=restarted
    tags:
    - install-mysql