- hosts: mysql
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vagrant
    ansible_become: true
  tasks:
  - name: Starting Mysql Installation Tasks.
     include_role:
     mysql_version: 8.0
     mysql_version_repo: mysql{{ mysql_version|string |replace(".", "") }}-community
     when: mysql_proc_status.failed == true or mysql_force_installation == true
  tags:
    - install-mysql
     
- hosts: webservers
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vagrant
    ansible_become: true
    package: net-tools
    user: alex
    group: linux
  tasks:
  - name: Create group
    group:
      name: "{{group}}"

  - name: Create the user 
    user:
      name: "{{user}}"
      comment: Alex
      uid: 1055
      group: "{{group}}"

  - name: Install package
    yum:
      name: "{{package}}"
      state: latest

  - name: Copy group file
    copy:
      src: /etc/group
      dest: /tmp/group.back

  - name: Create a directory 
    file:
      path: /tmp/linux
      state: directory
      mode: '0755'

  - name: Firewall add httpd
    firewalld:
      service: http
      permanent: yes
      state: enabled
    notify:
      - reload firewalld

  - name: Flush handlers
    meta: flush_handlers

  - name: Executing a Command Using Shell Module 
    shell: netstat -an > temp.txt

